name: Build & Push
description: Build and push the Docker image to the registry.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref: branch|tag|SHA'
        type: string
        required: false
        default: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Set up Python
        uses: actions/setup-python@v6
      - name: install Poetry
        run: pipx install poetry==2.3.2
      