name: Build & Push
description: Build and push the Docker image to the registry.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref: branch|tag|SHA'
        type: string
        required: false
        default: main
      push-image:
        description: 'Push image to registry'
        type: boolean
        required: false
        default: false
  push:
    branches:
      - '*'
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get ref
        id: ref
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "branch" ]]; then
            echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.ref.outputs.ref }}
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
      - name: install Poetry
        run: pipx install poetry==2.3.2
      - name: install dependencies
        run: poetry install
      - name: run tests
        run: |
          poetry run nox -s tests
      - name: lint
        run: |
          poetry run nox -s lint
      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: options
        id: options
        env:
          BASE_TAG: ghcr.io/${{ github.repository }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            DOCKER_TAGS=${{ steps.docker-meta.outputs.tags }}
            PUSH_IMAGE=${{ github.event.inputs.push-image }}
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            DOCKER_TAGS=${{ env.BASE_TAG }}:${{ github.ref_name }}
            PUSH_IMAGE=true
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "branch" \
            && "${{ github.ref_name }}" == 'main' ]]; then
            DOCKER_TAGS=${{ env.BASE_TAG }}:latest
            PUSH_IMAGE=true
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "branch" \
            && "${{ github.ref_name }}" != 'main' ]]; then
            DOCKER_TAGS=${{ env.BASE_TAG }}:${{ github.ref_name }}
            PUSH_IMAGE=false
          fi
          echo "docker-tags=${DOCKER_TAGS}" >> $GITHUB_OUTPUT
          echo "push-image=${PUSH_IMAGE}" >> $GITHUB_OUTPUT
          echo "ref=${{ steps.ref.outputs.ref }}" >> $GITHUB_OUTPUT
          echo "python-version=${{ steps.setup-python.outputs.python-version }}" >> $GITHUB_OUTPUT
          echo "build-number=${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ steps.options.outputs.push-image }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.options.outputs.docker-tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
      - name: step summary
        uses: actions/github-script@v7
        with:
          script: |
            const name = 'docker/metadata-action';
            const json = {
              options: ${{ toJSON(steps.options.outputs) }},
              meta: ${{ toJSON(steps.docker-meta.outputs) }}
            };
            core.summary.addHeading(name, 3);
            core.summary.addCodeBlock(JSON.stringify(json, null, 4), 'json');
            core.summary.addEOL();
            core.summary.write();
